server:
  port: 7766

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bootdata
    username: postgres
    password: admin